version: '3.8'

services:
  payload-cms:
    image: node:18-alpine
    ports:
      - "80:3000"
    volumes:
      - ./cms/travelblog:/home/node/app
      - payload-node-modules:/home/node/app/node_modules
    working_dir: /home/node/app/
    command: sh -c "corepack enable && corepack prepare pnpm@latest --activate && pnpm install && pnpm dev"
    depends_on:
      - mongodb
    env_file:
      - ./cms/travelblog/.env
    networks:
      - app-network

  # Chat - MongoDB
  mongodb:
    image: mongo:6
    ports:
      - "27017:27017"
    volumes:
      - mongo-data:/data/db
    networks:
      - app-network

  # Chat - Backend (Java)
  chat-backend:
    build:
      context: ./chat/backend
      dockerfile: Dockerfile
    depends_on:
      - mongodb
    environment:
      - SPRING_DATA_MONGODB_URI=mongodb://mongodb:27017/chatdb
    networks:
      - app-network

  # Chat - Frontend (React)
  chat-frontend:
    build:
      context: ./chat/frontend
      dockerfile: Dockerfile
    ports:
      - "90:3000"
    depends_on:
      - chat-backend
    volumes:
      - ./chat/frontend:/app
      - /app/node_modules
    networks:
      - app-network

  # Chat - Nginx
  nginx:
    image: nginx:alpine
    ports:
      - "88:88"
    volumes:
      - ./chat/nginx/nginx.conf:/etc/nginx/nginx.conf:ro
    depends_on:
      - chat-backend
      - chat-frontend
    networks:
      - app-network

  # IA - Backend (Node.js)
  ia-backend:
    build:
      context: ./IA/backend
      dockerfile: Dockerfile
    ports:
      - "5001:5001"
    networks:
      - app-network

  # IA - Apache
  apache:
    build:
      context: ./IA/apache
      dockerfile: Dockerfile
    ports:
      - "5000:5000"
    depends_on:
      - ia-backend
    networks:
      - app-network

  # IA - Frontend (React)
  ia-frontend:
    build:
      context: ./IA/frontend
      dockerfile: Dockerfile
    ports:
      - "3001:80"
    depends_on:
      - apache
    networks:
      - app-network
  
networks:
  app-network:
    driver: bridge

volumes:
  mongo-data:
  payload-node-modules: