version: '3.8'

services:
  mongodb:
    image: mongo:6
    ports:
      - "27017:27017"
    volumes:
      - mongo-data:/data/db

  redis:
    image: redis:7-alpine
    ports:
      - "6379:6379"

  chat-backend:
    build:
      context: ./backend
      dockerfile: Dockerfile
    depends_on:
      - mongodb
      - redis
    environment:
      - SPRING_DATA_MONGODB_URI=mongodb://mongodb:27017/chatdb
      - SPRING_REDIS_HOST=redis
      - SPRING_REDIS_PORT=6379

  chat-frontend:
    build:
      context: ./frontend
      dockerfile: Dockerfile
    ports:
      - "90:3000"  # Expose port 90 externally, map to 3000 internally
    depends_on:
      - chat-backend
    volumes:
      - ./frontend:/app
      - /app/node_modules

  nginx:
    image: nginx:alpine
    ports:
      - "88:88"  # Expose Nginx on port 88
    volumes:
      - ./nginx/nginx.conf:/etc/nginx/nginx.conf:ro
    depends_on:
      - chat-backend
      - chat-frontend

volumes:
  mongo-data: