apiVersion: apps/v1
kind: Deployment
metadata:
  annotations:
    kompose.cmd: C:\Tools\kompose\kompose.exe convert --out kubernetes/
    kompose.version: 1.35.0 (9532ceef3)
  labels:
    io.kompose.service: apache
  name: apache
spec:
  replicas: 1
  selector:
    matchLabels:
      io.kompose.service: apache
  template:
    metadata:
      annotations:
        kompose.cmd: C:\Tools\kompose\kompose.exe convert --out kubernetes/
        kompose.version: 1.35.0 (9532ceef3)
      labels:
        io.kompose.service: apache
    spec:
      containers:
        - image: alexia0604/ia-apache:latest
          name: apache
          ports:
            - containerPort: 5000
              protocol: TCP
      restartPolicy: Always
