apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    io.kompose.service: chat-backend
  name: chat-backend
spec:
  replicas: 12
  selector:
    matchLabels:
      io.kompose.service: chat-backend
  template:
    metadata:
      labels:
        io.kompose.service: chat-backend
    spec:
      containers:
        - env:
            - name: SPRING_DATA_MONGODB_URI
              value: mongodb://mongodb:27017/chatdb
            - name: SPRING_REDIS_HOST
              value: redis
            - name: SPRING_REDIS_PORT
              value: "6379"
            - name: POD_NAME
              valueFrom:
                fieldRef:
                  fieldPath: metadata.name
            - name: POD_NAMESPACE
              valueFrom:
                fieldRef:
                  fieldPath: metadata.namespace
            - name: POD_IP
              valueFrom:
                fieldRef:
                  fieldPath: status.podIP
          image: alexia0604/chat-backend:latest
          name: chat-backend
          ports:
            - containerPort: 8080
              protocol: TCP
      restartPolicy: Always