apiVersion: v1
kind: Service
metadata:
  annotations:
    kompose.cmd: C:\Tools\kompose\kompose.exe convert --out kubernetes/
    kompose.version: 1.35.0 (9532ceef3)
  labels:
    io.kompose.service: ia-backend
  name: ia-backend
spec:
  ports:
    - name: "5001"
      port: 5001
      targetPort: 5001
  selector:
    io.kompose.service: ia-backend
