apiVersion: v1
kind: Service
metadata:
  labels:
    io.kompose.service: ia-frontend
  name: ia-frontend
spec:
  type: NodePort
  ports:
    - name: "3001"
      port: 3001
      targetPort: 80
      nodePort: 30301
  selector:
    io.kompose.service: ia-frontend