apiVersion: v1
data:
  nginx.conf: |-
    events {}

    http {
        upstream backend {
            server chat-backend:8080;  # Numele serviciului backend din docker-compose.yml
        }

        server {
            listen 88;

            # Redirecționează cererile WebSocket către backend
            location /chat-websocket {
                proxy_pass http://backend;
                proxy_http_version 1.1;
                proxy_set_header Upgrade $http_upgrade;
                proxy_set_header Connection "upgrade";
                proxy_set_header Host $host;
                proxy_set_header X-Real-IP $remote_addr;
            }

            # Redirecționează alte cereri (opțional, pentru debugging)
            location / {
                return 200 "Nginx is running on port 88. Access the chat client on port 90.";
            }
        }
    }
kind: ConfigMap
metadata:
  annotations:
    use-subpath: "true"
  labels:
    io.kompose.service: nginx
  name: nginx-cm0
