apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    io.kompose.service: payload-cms
  name: payload-cms
spec:
  replicas: 5  # Changed from 1 to 5
  selector:
    matchLabels:
      io.kompose.service: payload-cms
  template:
    metadata:
      labels:
        io.kompose.service: payload-cms
    spec:
      containers:
        - image: alexia0604/payload:latest
          name: payload-cms
          ports:
            - containerPort: 3000
              protocol: TCP
          env:
            - name: DATABASE_URI
              valueFrom:
                configMapKeyRef:
                  key: DATABASE_URI
                  name: payload-cms-env
            - name: PAYLOAD_SECRET
              valueFrom:
                configMapKeyRef:
                  key: PAYLOAD_SECRET
                  name: payload-cms-env
      restartPolicy: Always